language: android

jdk: 
  - oraclejdk8

android:
 components: 
 - tools
 - tools
 - platform-tools
 - build-tools-25.0.0
 - android-25
 - extra-android-m2repository
 
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
    
 before_install:
 - chmod +x gradlew
 
 sudo: required
